# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/qsample',
                'doc_host': 'https://JoaoH67.github.io',
                'git_url': 'https://github.com/JoaoH67/qsample',
                'lib_path': 'qsample'},
  'syms': {'qsample.core': {'qsample.core.foo': ('core.html#foo', 'qsample/core.py')}}}
