project:
  type: website

website:
  title: "Qsample"
  sidebar:
    contents:
      - section: "Examples"
        contents:
          - examples/Surface_code.ipynb
          - examples/GHZ.ipynb
          - examples/Teleportation.ipynb
          - examples/Steane.ipynb
